# Created using wingetcreate

PackageIdentifier: CCP.EveLauncher
PackageVersion: 1902445
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://binaries.eveonline.com/EveLauncher-1902445.exe
  InstallerSha256: 2BB3598751D3DF303CB26B989A12B919B528DB4F0C9C23D59F423FD69BA9CE42
ManifestType: installer
ManifestVersion: 1.0.0
